cache: bundler
language: ruby
sudo: false


before_install:
  - gem update --system
  - gem install bundler

gemfile:
  - gemfiles/rails_4.0.13.gemfile
  - gemfiles/rails_4.1.16.gemfile
  - gemfiles/rails_4.2.11.gemfile
  - gemfiles/rails_5.0.7.gemfile
  - gemfiles/rails_5.1.6.gemfile
  - gemfiles/rails_5.2.2.gemfile

matrix:
  exclude:
    - gemfile: gemfiles/rails_4.0.13.gemfile
      rvm: 2.4.4
    - gemfile: gemfiles/rails_4.0.13.gemfile
      rvm: 2.5.1
    - gemfile: gemfiles/rails_4.1.16.gemfile
      rvm: 2.4.4
    - gemfile: gemfiles/rails_4.1.16.gemfile
      rvm: 2.5.1

rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
