cache: bundler
language: ruby
sudo: false

before_install:
  - gem update --system
  - gem install bundler

gemfile:
  - gemfiles/rails_5.0.7.gemfile
  - gemfiles/rails_5.1.7.gemfile
  - gemfiles/rails_5.2.3.gemfile
  - gemfiles/rails_5.2.4.gemfile
  - gemfiles/rails_6.0.3.gemfile

rvm:
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.1

matrix:
  exclude:
    - gemfile: gemfiles/rails_6.0.3.gemfile
      rvm: 2.4.10
