language: ruby
sudo: false
cache: bundler

rvm:
  - 2.1.9
  - 2.2.6
  - 2.3.3

gemfile:
  - gemfiles/rails_4.0.0.gemfile
  - gemfiles/rails_4.0.1.gemfile
  - gemfiles/rails_4.0.2.gemfile
  - gemfiles/rails_4.0.3.gemfile
  - gemfiles/rails_4.0.4.gemfile
  - gemfiles/rails_4.0.5.gemfile
  - gemfiles/rails_4.0.6.gemfile
  - gemfiles/rails_4.0.7.gemfile
  - gemfiles/rails_4.0.8.gemfile
  - gemfiles/rails_4.0.9.gemfile
  - gemfiles/rails_4.0.10.gemfile
  - gemfiles/rails_4.0.11.gemfile
  - gemfiles/rails_4.0.11.1.gemfile
  - gemfiles/rails_4.0.12.gemfile
  - gemfiles/rails_4.0.13.gemfile
  - gemfiles/rails_4.1.0.gemfile
  - gemfiles/rails_4.1.1.gemfile
  - gemfiles/rails_4.1.2.gemfile
  - gemfiles/rails_4.1.3.gemfile
  - gemfiles/rails_4.1.4.gemfile
  - gemfiles/rails_4.1.5.gemfile
  - gemfiles/rails_4.1.6.gemfile
  - gemfiles/rails_4.1.7.gemfile
  - gemfiles/rails_4.1.7.1.gemfile
  - gemfiles/rails_4.1.8.gemfile
  - gemfiles/rails_4.1.9.gemfile
  - gemfiles/rails_4.1.10.gemfile
  - gemfiles/rails_4.1.11.gemfile
  - gemfiles/rails_4.1.12.gemfile
  - gemfiles/rails_4.1.13.gemfile
  - gemfiles/rails_4.1.14.gemfile
  - gemfiles/rails_4.1.14.1.gemfile
  - gemfiles/rails_4.1.14.2.gemfile
  - gemfiles/rails_4.1.15.gemfile
  - gemfiles/rails_4.2.0.gemfile
  - gemfiles/rails_4.2.1.gemfile
  - gemfiles/rails_4.2.2.gemfile
  - gemfiles/rails_4.2.3.gemfile
  - gemfiles/rails_4.2.4.gemfile
  - gemfiles/rails_4.2.5.gemfile
  - gemfiles/rails_4.2.5.1.gemfile
  - gemfiles/rails_4.2.5.2.gemfile
  - gemfiles/rails_4.2.6.gemfile
  - gemfiles/rails_4.2.7.gemfile
  - gemfiles/rails_4.2.7.1.gemfile
  - gemfiles/rails_4.2.8.gemfile
  - gemfiles/rails_5.0.0.gemfile
  - gemfiles/rails_5.0.0.1.gemfile
  - gemfiles/rails_5.0.1.gemfile
  - gemfiles/rails_5.0.2.gemfile
  - gemfiles/rails_5.1.0.rc1.gemfile

matrix:
  include:
    - rvm: 2.4.1
      gemfile: gemfiles/rails_4.2.8.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_5.0.0.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_5.0.0.1.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_5.0.1.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_5.0.2.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails_5.1.0.rc1.gemfile
  exclude:
    # Rails 5.0+ requires a minimum of Ruby 2.2.2.
    - rvm: 2.1.9
      gemfile: gemfiles/rails_5.0.0.gemfile
    - rvm: 2.1.9
      gemfile: gemfiles/rails_5.0.0.1.gemfile
    - rvm: 2.1.9
      gemfile: gemfiles/rails_5.0.1.gemfile
    - rvm: 2.1.9
      gemfile: gemfiles/rails_5.0.2.gemfile
    - rvm: 2.1.9
      gemfile: gemfiles/rails_5.1.0.rc1.gemfile
    # These Rails versions are broken with the latest Ruby versions.
    # They are fixed in the next version:
    # https://github.com/rails/rails/blob/v4.0.6/activerecord/CHANGELOG.md
    # https://github.com/rails/rails/blob/v4.1.2/activerecord/CHANGELOG.md
    - rvm: 2.2.6
      gemfile: gemfiles/rails_4.0.0.gemfile
    - rvm: 2.2.6
      gemfile: gemfiles/rails_4.0.1.gemfile
    - rvm: 2.2.6
      gemfile: gemfiles/rails_4.0.2.gemfile
    - rvm: 2.2.6
      gemfile: gemfiles/rails_4.0.3.gemfile
    - rvm: 2.2.6
      gemfile: gemfiles/rails_4.0.4.gemfile
    - rvm: 2.2.6
      gemfile: gemfiles/rails_4.0.5.gemfile
    - rvm: 2.2.6
      gemfile: gemfiles/rails_4.1.0.gemfile
    - rvm: 2.2.6
      gemfile: gemfiles/rails_4.1.1.gemfile
    - rvm: 2.3.3
      gemfile: gemfiles/rails_4.0.0.gemfile
    - rvm: 2.3.3
      gemfile: gemfiles/rails_4.0.1.gemfile
    - rvm: 2.3.3
      gemfile: gemfiles/rails_4.0.2.gemfile
    - rvm: 2.3.3
      gemfile: gemfiles/rails_4.0.3.gemfile
    - rvm: 2.3.3
      gemfile: gemfiles/rails_4.0.4.gemfile
    - rvm: 2.3.3
      gemfile: gemfiles/rails_4.0.5.gemfile
    - rvm: 2.3.3
      gemfile: gemfiles/rails_4.1.0.gemfile
    - rvm: 2.3.3
      gemfile: gemfiles/rails_4.1.1.gemfile
