cache: bundler
language: ruby
sudo: false

before_install:
  - gem update --system
  - gem install bundler

gemfile:
  - gemfiles/rails_4.2.11.gemfile
  - gemfiles/rails_5.0.7.gemfile
  - gemfiles/rails_5.1.6.gemfile
  - gemfiles/rails_5.2.3.gemfile
  - gemfiles/rails_5.2.4.gemfile
  - gemfiles/rails_6.0.1.gemfile

rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3

matrix:
  exclude:
    - gemfile: gemfiles/rails_6.0.1.gemfile
      rvm: 2.4.6
