language: ruby
sudo: false
cache: bundler

rvm:
  - 2.2.10
  - 2.3.7

gemfile:
  - gemfiles/rails_4.0.13.gemfile
  - gemfiles/rails_4.1.16.gemfile
  - gemfiles/rails_4.2.10.gemfile
  - gemfiles/rails_5.0.7.gemfile
  - gemfiles/rails_5.1.6.gemfile
  - gemfiles/rails_5.2.0.gemfile
