cache: bundler
language: ruby
sudo: false


before_install:
  - gem update --system
  - gem install bundler

gemfile:
  - gemfiles/rails_4.2.11.gemfile
  - gemfiles/rails_5.0.7.gemfile
  - gemfiles/rails_5.1.6.gemfile
  - gemfiles/rails_5.2.2.gemfile

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
